title: Hailey's Portfolio
description: A collection of my technical writing work!
theme: just-the-docs

favicon_ico: /favicon.png

url: https://https://haileytapia.github.io/portfolio/

aux_links:
  "Email":
    - "mailto:ha596874@ucf.edu"
  "LinkedIn":
    - "https://www.linkedin.com/in/haileytapia/"

callouts:
  important:
    title: Important
    color: red
  note:
    title: Note
    color: grey-dk
  about:
    title: About
    color: purple
  tip:
    title: Tip
    color: green
