title: Hailey's Portfolio
description: A collection of my technical writing work!
theme: just-the-docs

favicon_ico: /favicon.png

url: https://https://haileytapia.github.io/portfolio/

aux_links:
  "Email":
    - "mailto:haileytap@outlook.com"
  "LinkedIn":
    - "https://www.linkedin.com/in/haileytapia/"

enable_copy_code_button: true

compress_html:
  ignore:
    envs: all
    
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: grey-dk
  about:
    title: About
    color: purple
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: blue  
