title: Hailey's Portfolio
description: A collection of my technical writing work!
theme: just-the-docs

favicon_ico: /favicon.png

url: https://haileytapia.github.io

aux_links:
  "Email":
    - "mailto:haileytapia@knights.ucf.edu"
  "LinkedIn":
    - "https://www.linkedin.com/in/haileytapia/"

callouts:
  important:
    title: Important
    color: red
  note:
    title: Note
    color: grey-lt
  about:
    title: About
    color: purple
